// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpU6osiX37DiigF3EX5hb8J9D20JdaLFs',
    appId: '1:747981452803:web:5ec6df2c32dd662f820036',
    messagingSenderId: '747981452803',
    projectId: 'medsense-492f8',
    authDomain: 'medsense-492f8.firebaseapp.com',
    storageBucket: 'medsense-492f8.firebasestorage.app',
    measurementId: 'G-PW2RJSCZT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMBqk3XNt22hximmdQsKcNv4hBWq7mmQ',
    appId: '1:747981452803:android:0f35873d68902006820036',
    messagingSenderId: '747981452803',
    projectId: 'medsense-492f8',
    storageBucket: 'medsense-492f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9DEQs4t8TtShgzDAfFL6dUF7GPoJ-N8',
    appId: '1:747981452803:ios:70c11da3ddaa29fb820036',
    messagingSenderId: '747981452803',
    projectId: 'medsense-492f8',
    storageBucket: 'medsense-492f8.firebasestorage.app',
    iosBundleId: 'com.example.medSenseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ9DEQs4t8TtShgzDAfFL6dUF7GPoJ-N8',
    appId: '1:747981452803:ios:70c11da3ddaa29fb820036',
    messagingSenderId: '747981452803',
    projectId: 'medsense-492f8',
    storageBucket: 'medsense-492f8.firebasestorage.app',
    iosBundleId: 'com.example.medSenseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpU6osiX37DiigF3EX5hb8J9D20JdaLFs',
    appId: '1:747981452803:web:0b7afac53f58c6d4820036',
    messagingSenderId: '747981452803',
    projectId: 'medsense-492f8',
    authDomain: 'medsense-492f8.firebaseapp.com',
    storageBucket: 'medsense-492f8.firebasestorage.app',
    measurementId: 'G-1T32VT2W66',
  );

}